### ISSUE TITLE
Noisy kind annotations

### ISSUE THREAD

**Issue by sjakobi** [sjakobi/haddock#5]
We currently generate additional kind signatures that in general seem to be more noisy than helpful. E.g. in `microlens`:

![image](https://user-images.githubusercontent.com/3664523/42758549-3a8473ba-8904-11e8-9613-005fbfc2d287.png)

**Comment by sjakobi** [comment]
`--show-iface` shows the same type:

```
type LensLike' (f :: * -> *) s a = LensLike f s s a a
```

**Comment by alexbiehl** [comment]
I checked IfaceSyn, kind signatures are not supressable

**Comment by sjakobi** [comment]
We might be able to remove the kind signatures from the declarations. But in that case we'd probably also remove the optional explicit kind signatures that were added on purpose.

**Comment by RyanGlScott** [comment]
This is the line that adds this: https://github.com/haskell/haddock/blob/4abf7d4979b5364da59f7412a3d7143aea26cf7e/haddock-api/src/Haddock/Convert.hs#L371

Personally, I'd be loathe to remove this. I like being able to tell at a glance what the kind of each type variable is.

**Comment by harpocrates** [comment]
I agree with @RyanGlScott about preferring the kind signatures.

**Comment by sjakobi** [comment]
https://github.com/haskell/haddock/pull/915 seems to remove much of the noise, but keeps kind signatures where they are useful.
